version: 2.1
defaults: &defaults
  working_directory: /home/circleci/nw-dashboard
  docker:
    - image: circleci/node:latest

workflows:
  version: 2
  dependencies_and_build:
    jobs:
      - dependencies
      - build:
          requires:
            - dependencies
      - deploy:
          requires:
            - build

jobs:
  dependencies:
    <<: *defaults

    steps:
      - checkout
      - run:
          name: install-deps
          command: 'sudo yarn install'
  build:
    <<: *defaults

    steps:
      - checkout
      - run:
          name: install-deps
          command: 'sudo yarn install'
      - run:
          name: build
          command: 'yarn build'
  deploy:
    <<: *defaults

    steps:
      - checkout
      - run:
          name: install-deps
          command: 'sudo yarn install'
      - run:
          name: build
          command: 'yarn build'
      - add_ssh_keys
      - run: echo 'boniweb.ch ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDaejNRvQMyo+E4p6MSqfE9lsb39Me3dIROQKOC7+1U8fj9uHg+cMa9t8JNmjxXPb0hyB9iV44C6tt9YGuF1xifCK5oGt1Iv0WFJ/c/Qjo9Yk/aH1XqMQNUGnZaAMCHeKbVxIVlw0HH4I+1sbqr5ZTPT8NmZzUcDbLi/Vl3TVgcqJZ+iGM0aQioQbVqYgf1umJYktAhRu0353Sgbt91rs8T0J8ENqfh0tg2XGAEj2Nz1ps6Vwuyo03fSoDk74qMyyAY2EKmxazjVAdzt56cqosh8NO86sREkpX3ZsAbm0SX4YcS2umXGIAtqKRCdv5mkn2cW4LO/KvnrGd7VH4j98lR' >> ~/.ssh/known_hosts
      - run: scp /home/circleci/nw-dashboard/dist ssh -o StrictHostKeyChecking=no boro@boniweb.ch:/var/www/aetherbergbau.com/ -P 22

