version: 2.1
defaults: &defaults
  working_directory: /home/circleci/nw-dashboard
  docker:
    - image: circleci/node:latest

jobs:
  build:
    <<: *defaults

    steps:
      - checkout
      - run:
          name: install-deps
          command: 'sudo yarn install'
      - run:
          name: "Ignore build warnings"
          command: echo 'export CI=false' >> $BASH_ENV
      - run:
          name: build
          command: 'yarn build'
      - add_ssh_keys:
          fingerprints:
            - "00:6f:05:7e:2d:55:71:31:d3:23:24:83:47:ca:12:1e"
      - run: echo 'boniweb.ch ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDaejNRvQMyo+E4p6MSqfE9lsb39Me3dIROQKOC7+1U8fj9uHg+cMa9t8JNmjxXPb0hyB9iV44C6tt9YGuF1xifCK5oGt1Iv0WFJ/c/Qjo9Yk/aH1XqMQNUGnZaAMCHeKbVxIVlw0HH4I+1sbqr5ZTPT8NmZzUcDbLi/Vl3TVgcqJZ+iGM0aQioQbVqYgf1umJYktAhRu0353Sgbt91rs8T0J8ENqfh0tg2XGAEj2Nz1ps6Vwuyo03fSoDk74qMyyAY2EKmxazjVAdzt56cqosh8NO86sREkpX3ZsAbm0SX4YcS2umXGIAtqKRCdv5mkn2cW4LO/KvnrGd7VH4j98lR' >> ~/.ssh/known_hosts
      - run:
          name: clean remote folder
          command: ssh boro@boniweb.ch "rm -rf /var/www/aetherbergbau.com/*"
      - run:
          name: upload to remote folder
          command: scp -r /home/circleci/nw-dashboard/build/. boro@boniweb.ch:/var/www/aetherbergbau.com

