version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: install-deps
          command: 'sudo yarn install'
      - run:
          name: run-tests
          command: 'yarn test'
      - run:
          name: build
          command: 'yarn build'
